### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by WarAndroid** [magistermaks/mod-redbits#4] opened 2020-12-02 12:00 UTC
Basically if you join with red bits installed into a server that don't support it, then game rendering is going crazy and every block is rendering as different one. (I tried with only this mod downloaded and it still have the same issue)

**Comment by magistermaks** [comment] 2020-12-02 13:07
By "don't support it" do you mean an older version? no red bits on the server? no fabric loader on the server? 
I may be wrong but that doesn't look like Red Bits fault.

**Comment by WarAndroid** [comment] 2020-12-03 14:31
By saying "don't support it" I mean a server either without red bits installed or vanilla one.

**Comment by magistermaks** [comment] 2020-12-03 19:21
Well I will look into it, but I'm 99% sure that that's the case with every single fabric mod. Maybe consider reporting it to the fabric API project?

**Comment by magistermaks** [comment] 2020-12-07 11:55
Yes I recreated this bug, but it isn't Red Bits specific as is also caused by other fabric mods, closing the issue

**Closed by magistermaks** 2020-12-07 11:55 UTC

**Comment by Qonsyuma** [comment] 2022-07-12 12:47
Small side info that this is still happening, though I'm not sure if it's now Red Bit's issue or not

**Comment by magistermaks** [comment] 2022-07-12 20:55
It's not, this is the expected behavior for most fabric mods
