### ISSUE TITLE
1.16.0   errors on load saying for mc 1.18

### ISSUE THREAD

**Issue by DemonSeedxp** [magistermaks/mod-redbits#14] opened 2023-09-05 04:48 UTC
when versions cover a range of mc versions  compatibility like 1.16.0 saying it's valid for 1.18.1 - 1.19.3 I've always assumed that also covered the other iterations between those two versions, but I dont know for sure. Is that correct and the 1.16.0 release should infact also work on 1.19.2, or no it is only for 1.18.1 and 1.19.3?

Whichever the case may be, it did still only mention 1.18 when it errored when i tried loading in 1.19.2

**Comment by magistermaks** [comment] 2023-09-07 20:31
the 1.16.0 version of redbits should support all minecraft versions between 1.18.0 and 1.19.3 (inclusive) 
if it fails for you on 1.19.2 that is a bug, please send the error log if you can

**Comment by magistermaks** [comment] 2023-10-01 00:15
closing as i'm unable to reproduce this, and there aren't any additional details provided

**Closed by magistermaks** 2023-10-01 00:15 UTC
